unit uChecknumerexistsClass;

//  *************************************************
//    Generated By: JsonToDelphiClass - 0.65
//    Project link: https://github.com/PKGeorgiev/Delphi-JsonToDelphiClass
//    Generated On: 2024-10-16 20:34:34
//  *************************************************
//    Created By  : Petar Georgiev - 2014
//    WebSite     : http://pgeorgiev.com
//  *************************************************

interface

uses Generics.Collections, Rest.Json;

type

TChecknumerexistsClass = class
private
  FExists: Boolean;
  FJid: String;
  FName: String;
  FNumber: String;
public
  property exists: Boolean read FExists write FExists;
  property jid: String read FJid write FJid;
  property name: String read FName write FName;
  property number: String read FNumber write FNumber;
  function ToJsonString: string;
  class function FromJsonString(AJsonString: string): TChecknumerexistsClass;
end;

TResultCheckNumberClass = class
private
  FChecknumerexists: TArray<TChecknumerexistsClass>;
public
  property checknumerexists: TArray<TChecknumerexistsClass> read FChecknumerexists write FChecknumerexists;
  destructor Destroy; override;
  function ToJsonString: string;
  class function FromJsonString(AJsonString: string): TResultCheckNumberClass;
end;

implementation

{TChecknumerexistsClass}


function TChecknumerexistsClass.ToJsonString: string;
begin
  result := TJson.ObjectToJsonString(self);
end;

class function TChecknumerexistsClass.FromJsonString(AJsonString: string): TChecknumerexistsClass;
begin
  result := TJson.JsonToObject<TChecknumerexistsClass>(AJsonString)
end;

{TResultCheckNumberClass}

destructor TResultCheckNumberClass.Destroy;
var
  LchecknumerexistsItem: TChecknumerexistsClass;
begin

 for LchecknumerexistsItem in FChecknumerexists do
   LchecknumerexistsItem.free;

  inherited;
end;

function TResultCheckNumberClass.ToJsonString: string;
begin
  result := TJson.ObjectToJsonString(self);
end;

class function TResultCheckNumberClass.FromJsonString(AJsonString: string): TResultCheckNumberClass;
begin
  result := TJson.JsonToObject<TResultCheckNumberClass>(AJsonString)
end;

end.
