unit uConnectionUpdateClass;

//  *************************************************
//    Generated By: JsonToDelphiClass - 0.65
//    Project link: https://github.com/PKGeorgiev/Delphi-JsonToDelphiClass
//    Generated On: 2024-05-27 22:59:29
//  *************************************************
//    Created By  : Petar Georgiev - 2014
//    WebSite     : http://pgeorgiev.com
//  *************************************************

interface

uses Generics.Collections, Rest.Json;

type

TDataClass = class
private
  FInstance: String;
  FState: String;
  FStatusReason: Extended;
public
  property instance: String read FInstance write FInstance;
  property state: String read FState write FState;
  property statusReason: Extended read FStatusReason write FStatusReason;
  function ToJsonString: string;
  class function FromJsonString(AJsonString: string): TDataClass;
end;

TResponseClass = class
private
  FApikey: String;
  FData: TDataClass;
  FDate_time: String;
  FDestination: String;
  FEvent: String;
  FInstance: String;
  FSender: String;
  FServer_url: String;
public
  property apikey: String read FApikey write FApikey;
  property data: TDataClass read FData write FData;
  property date_time: String read FDate_time write FDate_time;
  property destination: String read FDestination write FDestination;
  property event: String read FEvent write FEvent;
  property instance: String read FInstance write FInstance;
  property sender: String read FSender write FSender;
  property server_url: String read FServer_url write FServer_url;
  constructor Create;
  destructor Destroy; override;
  function ToJsonString: string;
  class function FromJsonString(AJsonString: string): TResponseClass;
end;

implementation

{TDataClass}


function TDataClass.ToJsonString: string;
begin
  result := TJson.ObjectToJsonString(self);
end;

class function TDataClass.FromJsonString(AJsonString: string): TDataClass;
begin
  result := TJson.JsonToObject<TDataClass>(AJsonString)
end;

{TResponseClass}

constructor TResponseClass.Create;
begin
  inherited;
  FData := TDataClass.Create();
end;

destructor TResponseClass.Destroy;
begin
  FData.free;
  inherited;
end;

function TResponseClass.ToJsonString: string;
begin
  result := TJson.ObjectToJsonString(self);
end;

class function TResponseClass.FromJsonString(AJsonString: string): TResponseClass;
begin
  result := TJson.JsonToObject<TResponseClass>(AJsonString)
end;

end.
