unit uEventsMessageDeleteClasses;

//  *************************************************
//    Generated By: JsonToDelphiClass - 0.65
//    Project link: https://github.com/PKGeorgiev/Delphi-JsonToDelphiClass
//    Generated On: 2024-03-12 21:09:40
//  *************************************************
//    Created By  : Petar Georgiev - 2014
//    WebSite     : http://pgeorgiev.com
//  *************************************************

interface

uses Generics.Collections, Rest.Json;

type

TDataClass = class
private
  FFromMe: Boolean;
  FId: String;
  FRemoteJid: String;
public
  property fromMe: Boolean read FFromMe write FFromMe;
  property id: String read FId write FId;
  property remoteJid: String read FRemoteJid write FRemoteJid;
  function ToJsonString: string;
  class function FromJsonString(AJsonString: string): TDataClass;
end;

TResultEventMessageDeleteClass = class
private
  FApikey: String;
  FData: TDataClass;
  FDate_time: String;
  FDestination: String;
  FEvent: String;
  FInstance: String;
  FSender: String;
  FServer_url: String;
public
  property apikey: String read FApikey write FApikey;
  property data: TDataClass read FData write FData;
  property date_time: String read FDate_time write FDate_time;
  property destination: String read FDestination write FDestination;
  property event: String read FEvent write FEvent;
  property instance: String read FInstance write FInstance;
  property sender: String read FSender write FSender;
  property server_url: String read FServer_url write FServer_url;
  constructor Create;
  destructor Destroy; override;
  function ToJsonString: string;
  class function FromJsonString(AJsonString: string): TResultEventMessageDeleteClass;
end;

implementation

{TDataClass}


function TDataClass.ToJsonString: string;
begin
  result := TJson.ObjectToJsonString(self);
end;

class function TDataClass.FromJsonString(AJsonString: string): TDataClass;
begin
  result := TJson.JsonToObject<TDataClass>(AJsonString)
end;

{TResultEventMessagesDeleteClassClass}

constructor TResultEventMessageDeleteClass.Create;
begin
  inherited;
  FData := TDataClass.Create();
end;

destructor TResultEventMessageDeleteClass.Destroy;
begin
  FData.free;
  inherited;
end;

function TResultEventMessageDeleteClass.ToJsonString: string;
begin
  result := TJson.ObjectToJsonString(self);
end;

class function TResultEventMessageDeleteClass.FromJsonString(AJsonString: string): TResultEventMessageDeleteClass;
begin
  result := TJson.JsonToObject<TResultEventMessageDeleteClass>(AJsonString)
end;

end.
