unit uEventsMessageUpdate2Classes;

//  *************************************************
//    Generated By: JsonToDelphiClass - 0.65
//    Project link: https://github.com/PKGeorgiev/Delphi-JsonToDelphiClass
//    Generated On: 2024-09-17 23:18:21
//  *************************************************
//    Created By  : Petar Georgiev - 2014
//    WebSite     : http://pgeorgiev.com
//  *************************************************

interface

uses Generics.Collections, Rest.Json;

type

TDataClass = class
private
  FFromMe: Boolean;
  FInstanceId: String;
  FKeyId: String;
  FMessageId: String;
  FParticipant: String;
  FRemoteJid: String;
  FStatus: String;
public
  property fromMe: Boolean read FFromMe write FFromMe;
  property instanceId: String read FInstanceId write FInstanceId;
  property keyId: String read FKeyId write FKeyId;
  property messageId: String read FMessageId write FMessageId;
  property participant: String read FParticipant write FParticipant;
  property remoteJid: String read FRemoteJid write FRemoteJid;
  property status: String read FStatus write FStatus;
  function ToJsonString: string;
  class function FromJsonString(AJsonString: string): TDataClass;
end;

TResultEventMessageUpdate2Class = class
private
  FApikey: String;
  FData: TDataClass;
  FDate_time: String;
  FDestination: String;
  FEvent: String;
  FInstance: String;
  FSender: String;
  FServer_url: String;
public
  property apikey: String read FApikey write FApikey;
  property data: TDataClass read FData write FData;
  property date_time: String read FDate_time write FDate_time;
  property destination: String read FDestination write FDestination;
  property event: String read FEvent write FEvent;
  property instance: String read FInstance write FInstance;
  property sender: String read FSender write FSender;
  property server_url: String read FServer_url write FServer_url;
  constructor Create;
  destructor Destroy; override;
  function ToJsonString: string;
  class function FromJsonString(AJsonString: string): TResultEventMessageUpdate2Class;
end;

implementation

{TDataClass}


function TDataClass.ToJsonString: string;
begin
  result := TJson.ObjectToJsonString(self);
end;

class function TDataClass.FromJsonString(AJsonString: string): TDataClass;
begin
  result := TJson.JsonToObject<TDataClass>(AJsonString)
end;

{TResultEventMessageUpdate2Class}

constructor TResultEventMessageUpdate2Class.Create;
begin
  inherited;
  FData := TDataClass.Create();
end;

destructor TResultEventMessageUpdate2Class.Destroy;
begin
  FData.free;
  inherited;
end;

function TResultEventMessageUpdate2Class.ToJsonString: string;
begin
  result := TJson.ObjectToJsonString(self);
end;

class function TResultEventMessageUpdate2Class.FromJsonString(AJsonString: string): TResultEventMessageUpdate2Class;
begin
  result := TJson.JsonToObject<TResultEventMessageUpdate2Class>(AJsonString)
end;

end.
