unit uFetchInstancesClass;

//  *************************************************
//    Generated By: JsonToDelphiClass - 0.65
//    Project link: https://github.com/PKGeorgiev/Delphi-JsonToDelphiClass
//    Generated On: 2024-05-27 21:46:52
//  *************************************************
//    Created By  : Petar Georgiev - 2014
//    WebSite     : http://pgeorgiev.com
//  *************************************************

interface

uses Generics.Collections, Rest.Json;

type

TInstanceClass = class
private
  FApikey: String;
  FInstanceId: String;
  FInstanceName: String;
  FOwner: String;
  FProfileName: String;
  FProfilePictureUrl: String;
  FProfileStatus: String;
  FServerUrl: String;
  FStatus: String;
public
  property apikey: String read FApikey write FApikey;
  property instanceId: String read FInstanceId write FInstanceId;
  property instanceName: String read FInstanceName write FInstanceName;
  property owner: String read FOwner write FOwner;
  property profileName: String read FProfileName write FProfileName;
  property profilePictureUrl: String read FProfilePictureUrl write FProfilePictureUrl;
  property profileStatus: String read FProfileStatus write FProfileStatus;
  property serverUrl: String read FServerUrl write FServerUrl;
  property status: String read FStatus write FStatus;
  function ToJsonString: string;
  class function FromJsonString(AJsonString: string): TInstanceClass;
end;

TFetchInstancesClass = class
private
  FInstance: TInstanceClass;
public
  property instance: TInstanceClass read FInstance write FInstance;
  constructor Create;
  destructor Destroy; override;
  function ToJsonString: string;
  class function FromJsonString(AJsonString: string): TFetchInstancesClass;
end;

TRootClass = class
private
  FFetchInstances: TArray<TFetchInstancesClass>;
public
  property FetchInstances: TArray<TFetchInstancesClass> read FFetchInstances write FFetchInstances;
  destructor Destroy; override;
  function ToJsonString: string;
  class function FromJsonString(AJsonString: string): TRootClass;
end;

implementation

{TInstanceClass}


function TInstanceClass.ToJsonString: string;
begin
  result := TJson.ObjectToJsonString(self);
end;

class function TInstanceClass.FromJsonString(AJsonString: string): TInstanceClass;
begin
  result := TJson.JsonToObject<TInstanceClass>(AJsonString)
end;

{TFetchInstancesClass}

constructor TFetchInstancesClass.Create;
begin
  inherited;
  FInstance := TInstanceClass.Create();
end;

destructor TFetchInstancesClass.Destroy;
begin
  FInstance.free;
  inherited;
end;

function TFetchInstancesClass.ToJsonString: string;
begin
  result := TJson.ObjectToJsonString(self);
end;

class function TFetchInstancesClass.FromJsonString(AJsonString: string): TFetchInstancesClass;
begin
  result := TJson.JsonToObject<TFetchInstancesClass>(AJsonString)
end;

{TRootClass}

destructor TRootClass.Destroy;
var
  LFetchInstancesItem: TFetchInstancesClass;
begin

 for LFetchInstancesItem in FFetchInstances do
   LFetchInstancesItem.free;

  inherited;
end;

function TRootClass.ToJsonString: string;
begin
  result := TJson.ObjectToJsonString(self);
end;

class function TRootClass.FromJsonString(AJsonString: string): TRootClass;
begin
  result := TJson.JsonToObject<TRootClass>(AJsonString)
end;

end.

