unit uQrcodeUpdateClass;

//  *************************************************
//    Generated By: JsonToDelphiClass - 0.65
//    Project link: https://github.com/PKGeorgiev/Delphi-JsonToDelphiClass
//    Generated On: 2024-05-27 23:49:18
//  *************************************************
//    Created By  : Petar Georgiev - 2014
//    WebSite     : http://pgeorgiev.com
//  *************************************************

interface

uses Generics.Collections, Rest.Json;

type

TQrcodeClass = class
private
  FBase64: String;
  FCode: String;
  FInstance: String;
public
  property base64: String read FBase64 write FBase64;
  property code: String read FCode write FCode;
  property instance: String read FInstance write FInstance;
  function ToJsonString: string;
  class function FromJsonString(AJsonString: string): TQrcodeClass;
end;

TDataClass = class
private
  FQrcode: TQrcodeClass;
public
  property qrcode: TQrcodeClass read FQrcode write FQrcode;
  constructor Create;
  destructor Destroy; override;
  function ToJsonString: string;
  class function FromJsonString(AJsonString: string): TDataClass;
end;

TResponseQrCodeClass = class
private
  FApikey: String;
  FData: TDataClass;
  FDate_time: String;
  FDestination: String;
  FEvent: String;
  FInstance: String;
  FSender: String;
  FServer_url: String;
public
  property apikey: String read FApikey write FApikey;
  property data: TDataClass read FData write FData;
  property date_time: String read FDate_time write FDate_time;
  property destination: String read FDestination write FDestination;
  property event: String read FEvent write FEvent;
  property instance: String read FInstance write FInstance;
  property sender: String read FSender write FSender;
  property server_url: String read FServer_url write FServer_url;
  constructor Create;
  destructor Destroy; override;
  function ToJsonString: string;
  class function FromJsonString(AJsonString: string): TResponseQrCodeClass;
end;

implementation

{TQrcodeClass}


function TQrcodeClass.ToJsonString: string;
begin
  result := TJson.ObjectToJsonString(self);
end;

class function TQrcodeClass.FromJsonString(AJsonString: string): TQrcodeClass;
begin
  result := TJson.JsonToObject<TQrcodeClass>(AJsonString)
end;

{TDataClass}

constructor TDataClass.Create;
begin
  inherited;
  FQrcode := TQrcodeClass.Create();
end;

destructor TDataClass.Destroy;
begin
  FQrcode.free;
  inherited;
end;

function TDataClass.ToJsonString: string;
begin
  result := TJson.ObjectToJsonString(self);
end;

class function TDataClass.FromJsonString(AJsonString: string): TDataClass;
begin
  result := TJson.JsonToObject<TDataClass>(AJsonString)
end;

{TResponseQrCodeClass}

constructor TResponseQrCodeClass.Create;
begin
  inherited;
  FData := TDataClass.Create();
end;

destructor TResponseQrCodeClass.Destroy;
begin
  FData.free;
  inherited;
end;

function TResponseQrCodeClass.ToJsonString: string;
begin
  result := TJson.ObjectToJsonString(self);
end;

class function TResponseQrCodeClass.FromJsonString(AJsonString: string): TResponseQrCodeClass;
begin
  result := TJson.JsonToObject<TResponseQrCodeClass>(AJsonString)
end;

end.
